элемент дерево файлов
Leftbrained-Inc/multimark pull request #73
Opened 2023-11-01 10:53 UTC by Qwan-Chi

элемент дерево файлов 
ОДОБРИТЕ ПЖ

2023-11-01 11:10 UTC, pank-su requested changes

2023-11-01 11:10 UTC, pank-su commented on build.gradle.kts
Удалить неиспользуемые библиотеки

2023-11-01 11:10 UTC, pank-su commented on src/commonMain/kotlin/App.kt
У этого файла вернуть обратно изменения, так как удалён в master

2023-11-01 11:10 UTC, pank-su commented on src/commonMain/kotlin/navigation/RootNode.kt
После работы вернуть LaunchScreen

2023-11-01 11:10 UTC, pank-su commented on src/commonMain/kotlin/ui/components/FileTree.kt
Сделать так, можно было передать структуру в виде вложенных списков и по ним сделать дерево файлов.

- [ ] придумать классы или списки для опр. структуры
- [ ] реализовать логику 

На данный момент это пока ничего, хорошо что ты разобрался чуть-чуть, но надо сделать так чтобы это было изменяемо.

2023-11-01 11:23 UTC, bulkabuka commented
# Требования к элементу

## Внешний вид

Компонент будет иметь вертикальный список, где каждый элемент списка представляет собой файл или каталог. Каталоги будут иметь иконку-индикатор, показывающую, раскрыт он или нет. Файлы могут иметь собственные иконки, отражающие их тип. Каждый элемент будет иметь подпись с названием файла или каталога. При нажатии на элемент списка, если это каталог, он раскрывается, показывая содержащиеся в нем файлы и подкаталоги.

## Логика

При инициализации компонента, он получает начальный путь к каталогу, который будет отображен. Затем он сканирует этот каталог, получая список файлов и подкаталогов. Этот список затем используется для создания всех элементов.

При нажатии на элемент списка, происходит проверка, является ли этот элемент файлом или каталогом. Если это файл, то может быть вызвано соответствующее действие (например, открытие файла). Если это каталог, то он либо раскрывается, показывая содержащиеся в нем файлы и подкаталоги, либо, если он уже был раскрыт, снова сворачивается.

> Все изменения в структуре файлов и каталогов (например, добавление или удаление файлов) должны автоматически отражаться в компоненте дерева файлов.

2023-11-01 11:59 UTC, bulkabuka requested changes
Доработать тесты, добавить автоматическое собирание структуры директорий и файлов

2023-11-03 07:23 UTC, Qwan-Chi commented
ПримиПж

2023-11-03 07:24 UTC, Qwan-Chi commented
ОДОБРИТЕ ПЖ

2023-11-03 07:32 UTC, bulkabuka approved these changes
Все еще достоин

2023-11-03 07:33 UTC, merged