Добавил ToolBar
Leftbrained-Inc/multimark pull request #87
Opened 2023-11-07 09:26 UTC by Shizik-tech

2023-11-07 09:28 UTC, pank-su requested changes

2023-11-08 06:30 UTC, pank-su requested changes
Добавь структуру, которая будет содержать опр. действие, которое будет происходить на опр. нажатие.

2023-11-08 07:07 UTC, pank-su approved these changes
ок

2023-11-08 07:11 UTC, bulkabuka approved these changes
СТУЛ

2023-11-08 07:11 UTC, merged